### ISSUE TITLE
Cannot open example app on iOS. iOS support broken / not clear

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/boltz-dart#5]
```Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)

    Finding Podfile changes
      - Flutter
      - boltz_dart

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `boltz_dart` from `.symlinks/plugins/boltz_dart/ios`
    [!] The `boltz_dart` pod failed to validate due to 1 error:
        - ERROR | attributes: Missing required attribute `source`.
        - WARN  | license: Missing license type.
        - WARN  | description: The description is shorter than the summary.
```

**Comment by i5hi** [comment]
Yah, this wont work, iOS is not supported yet. 

Sorry about the confusion.

**Comment by i5hi** [comment]
Btw @JoaoLobo94 iOS support for this repo will likely happen first and lwk-dart will be able to immediately inherit it.

**Comment by Saleciani** [comment]
Are there any plans even if distant to support web?
Both for here and lwk-dart

**Comment by i5hi** [comment]
No, not from our end, but we are open to reviewing and merging and related PRs.

**Comment by i5hi** [comment]
Hey @JoaoLobo94 Please attempt this again.

@salvatoto Has got iOS support merged and binaries are published as of 0.1.5

We need to get this working to validate that we are `iOS compatible` - we can then use the same builds and example for lwk.

**Comment by Saleciani** [comment]
Yeah, i can confirm it compiles well.

But it seems that the only accepted version is ios 17.5, is this correct?

So our apps would only be avaliable on the latest version os ios?

**Comment by i5hi** [comment]
Thats strange. Not sure why that is the case.

**Comment by salvatoto** [comment]
@JoaoLobo94 @i5hi I'm having trouble building iOS from the boltz-dart repo. Can build and run the boltz-dart package in our flutter app from a local copy overriden in pubspec.

So compilation is fine, but there is one small step not working in the copy/zip phase of the xcframework it seems. Will look.

@JoaoLobo94 Not sure where you're getting ios 17.5. I've been testing on 16.x fine, and our Flutter runner still has a min deployment of 13

**Comment by i5hi** [comment]
Let me check right now. I just updated binaries and some structures today. Let me see if there was an issue with the uploaded binaries.

**Comment by i5hi** [comment]
My bad. I thought I had changed loader to use `.a` and not `.dylib` - but it was not updated on trunk. Fixed. 

@salvatoto Try again with `flutter clean && flutter packages upgrade` and let me know.

**Comment by salvatoto** [comment]
Will check. I actually am building fine in iOS/cocoapods with our fork, which is at the same state as when you merged the ios build PR.

However, looks like you changed the interface after that so can't build on trunk right now.

@JoaoLobo94 `But it seems that the only accepted version is ios 17.5, is this correct?` This looks like just a warning on pod validation.

**Comment by i5hi** [comment]
Yes. We removed all the legacy code which boltz does not want new clients using. Also made updates to the Fees structure - which is based on v2.

**Comment by i5hi** [comment]
should all work smoothly now. we are using cargokit so builds are done locally by the end user. We will update the docs to ensure that the end user has the toolchain to do so.

Eventually we will use cargokit's precompiled binaries which will not require the user to have the toolchain and compile binaries themselves.
