### ISSUE TITLE
Adding referral id parameter

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/boltz-dart#6]
As per boltz documentation there is an option to partner up with them for smaller developers to monetize their applications.

It would be a great addition to add referral id string param (optional) to the dart bindings

This would implicate from my investigation adding in boltz-rust somewhere here

```
pub struct CreateSwapRequest {
    pub from: String,
    pub to: String,
    pub invoice: String,
    pub refund_public_key: PublicKey,
    ***
    pub referral_id: String
}
```

and

```
pub struct CreateReverseReq {
    pub invoice_amount: u32,
    pub from: String,
    pub to: String,
    pub preimage_hash: sha256::Hash,
    pub claim_public_key: PublicKey,
   ***
    pub referral_id: String
}
```

and then this would be used in the post for 

/swap/reverse
and
/swap/submarine

We then need to bring this up to the bolt-dart library as a param to for example

 ````
static Future<BtcLnBoltzSwap> newReverse(
      {required String mnemonic,
      required int index,
      required int outAmount,
      required bridge.Chain network,
      required String electrumUrl,
      required String boltzUrl,
      ******
      String? referralId
      ******
      required String pairHash, .....
```

**Comment by i5hi** [comment]
Thanks for the issue!

We have updated boltz-rust to support referralId.

boltz-rust is in the process of a big update which adds the v2 taproot api. Once that is complete, we will update boltz-dart and this will be supported.
