### ISSUE TITLE
Error installing locally with updated version.

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/boltz-dart#7]
<img width="1634" alt="image" src="https://github.com/SatoshiPortal/boltz-dart/assets/47111823/47d27b43-402f-49f3-b13c-14993440a83c">

**Comment by Saleciani** [comment]
Maybe a local path was forgotten somewhere? 
I do not think it is on my side since I tried to install directly from this example app and from my app that I am building, installing the previous version works fine, upgrading it, makes it fail

**Comment by i5hi** [comment]
fixed.

**Comment by i5hi** [comment]
also note that you have to call BoltzCore.init() in your apps main()

**Comment by i5hi** [comment]
run `flutter packages upgrade`

also, check out the tests folder to see updated usage.
